name: ig-reel-downloader

services:
  downloader:
    build: .
    volumes:
      - ./${OUTPUT_DIR:-output}:/app/${OUTPUT_DIR:-output}
      - ./assets:/app/assets
      - ./.env:/app/.env
      - ./data:/app/data
