#!/usr/bin/env python3
"""Persist a runner-local dashboard credential once; never emit secrets."""

import os
import secrets
import sys
from pathlib import Path
from urllib.parse import quote


def prepare(directory: Path, database: str) -> None:
    if not database:
        raise ValueError("POSTGRES_DB is required")
    destination = directory / ".dashboard.env"
    if destination.exists():
        if destination.is_symlink() or not destination.is_file():
            raise ValueError("Dashboard credential path must be a regular file")
        destination.chmod(0o600)
        return
    password = secrets.token_hex(32)
    content = (
        "# Generated by deployment; preserve across redeployments and restores.\n"
        "DB_DASHBOARD_USER=db_dashboard\n"
        f"DB_DASHBOARD_PASSWORD={password}\n"
        f"DASHBOARD_DATABASE_URL=postgresql+psycopg://db_dashboard:{password}"
        f"@postgres:5432/{quote(database, safe='')}\n"
    )
    temporary = directory / f".dashboard.env.{secrets.token_hex(8)}.tmp"
    try:
        fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, "w") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        # Atomic create without replacing a credential written by another deploy.
        os.link(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)


if __name__ == "__main__":
    try:
        prepare(Path(sys.argv[1]), os.environ.get("POSTGRES_DB", ""))
    except (OSError, ValueError):
        sys.exit(
            "Dashboard credential preparation failed; check deployment directory and POSTGRES_DB."
        )
