services:
  migrate:
    build: !reset null
    image: ghcr.io/jarki/idontwant_toopen_insta:${IMAGE_TAG:-prod}

  downloader:
    build: !reset null
    image: ghcr.io/jarki/idontwant_toopen_insta:${IMAGE_TAG:-prod}

  postgres-bootstrap:
    build: !reset null
    image: ghcr.io/jarki/idontwant_toopen_insta:${IMAGE_TAG:-prod}

  postgres-transfer:
    build: !reset null
    image: ghcr.io/jarki/idontwant_toopen_insta:${IMAGE_TAG:-prod}
